#!/bin/sh

## INSTALL does not clean up after ./configure or in subdirectories of src/;
## we do not have a ./configure, hence we only need the following:

ssdir=SuiteSparse
for sslib in SuiteSparse_config CXSparse AMD COLAMD CAMD CCOLAMD CHOLMOD; do
	(cd src/${ssdir}/${sslib} && make clean)
done
