library(Matrix)
mm <- Matrix(rnorm(500 * 150), nc = 150)
xpx <- crossprod(mm)
validObject(mm)
validObject(xpx)
str(mm)
str(xpx)
xpy <- crossprod(mm, rnorm(500))
res <- solve(xpx, xpy)
str(xpx)
validObject(xpx)
q("no")
